### ISSUE TITLE
Warning Appearing: Following warning is appearing multiple times in front end

### ISSUE THREAD

**Issue by AkshatGupta468** [AkshatGupta468/Employee_Transfer#9]
WARN  Possible Unhandled Promise Rejection (id: 2):
TypeError: Cannot read property 'data' of undefined
TypeError: Cannot read property 'data' of undefined
    at anonymous (http://10.10.5.146:8081/node_modules/expo/AppEntry.bundle//&platform=android&dev=true&hot=false&lazy=true:166440:39)
    at tryCallOne (/Users/kudo/01_Work/Repos/expo/expo/android/versioned-react-native/packages/react-native/ReactAndroid/hermes-engine/.cxx/MinSizeRel/3n472i6k/arm64-v8a/lib/InternalBytecode/InternalBytecode.js:53:16)
    at anonymous (/Users/kudo/01_Work/Repos/expo/expo/android/versioned-react-native/packages/react-native/ReactAndroid/hermes-engine/.cxx/MinSizeRel/3n472i6k/arm64-v8a/lib/InternalBytecode/InternalBytecode.js:139:27)
    at apply (native)
    at anonymous (http://10.10.5.146:8081/node_modules/expo/AppEntry.bundle//&platform=android&dev=true&hot=false&lazy=true:39627:26)
    at _callTimer (http://10.10.5.146:8081/node_modules/expo/AppEntry.bundle//&platform=android&dev=true&hot=false&lazy=true:39506:17)
    at _callReactNativeMicrotasksPass (http://10.10.5.146:8081/node_modules/expo/AppEntry.bundle//&platform=android&dev=true&hot=false&lazy=true:39551:17)
    at callReactNativeMicrotasks (http://10.10.5.146:8081/node_modules/expo/AppEntry.bundle//&platform=android&dev=true&hot=false&lazy=true:39757:44)
    at __callReactNativeMicrotasks (http://10.10.5.146:8081/node_modules/expo/AppEntry.bundle//&platform=android&dev=true&hot=false&lazy=true:3696:46)
    at anonymous (http://10.10.5.146:8081/node_modules/expo/AppEntry.bundle//&platform=android&dev=true&hot=false&lazy=true:3470:45)
    at __guard (http://10.10.5.146:8081/node_modules/expo/AppEntry.bundle//&platform=android&dev=true&hot=false&lazy=true:3669:15)
    at flushedQueue (http://10.10.5.146:8081/node_modules/expo/AppEntry.bundle//&platform=android&dev=true&hot=false&lazy=true:3469:21)
    at callFunctionReturnFlushedQueue (http://10.10.5.146:8081/node_modules/expo/AppEntry.bundle//&platform=android&dev=true&hot=false&lazy=true:3454:33)

**Comment by AkshatGupta468** [comment]
@SwapnilTatiya
